package com.fasttrans.transfer.domain.interfaces;

import com.fasttrans.transfer.domain.entities.Transfer;

/** Domain contract for enqueuing the transfer.requested event to the transactional outbox. */
public interface OutboxRepository {

    /**
     * Enqueues a transfer.requested event for the given transfer (serialized in infrastructure).
     * messageId is generated by the implementation; partition key = fromAccountRef.
     */
    void enqueueTransferRequested(Transfer transfer);
}
